# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jaffle Pancake
email:

#write html inside the double quotes to display in jumbotron
description: "<h1>The Mad Milliner</h1>"



baseurl:
url: "http://jpanken.github.io"
twitter_username: 
github_username:  jpanken

# Build settings
markdown: kramdown
